language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=2.0

matrix:
  exclude:
  - python: "3.3"
    env: DJANGO_VERSION=1.9
  - python: "3.3"
    env: DJANGO_VERSION=1.10
  - python: "3.3"
    env: DJANGO_VERSION=1.11
  - python: "3.3"
    env: DJANGO_VERSION=2.0

install:
  - pip install -r test_requirements.txt
  - pip install django==$DJANGO_VERSION
  - pip install -e .

script:
  - coverage run --source=save_the_change setup.py test

after_success:
  - codecov
